version: "3"
services:
  config-server:
    image: spring-cloud-example/config-server:latest

  rabbitmq:
    image: rabbitmq:3.8.2-management
    container_name: dataflow-rabbitmq
    expose:
      - 5672
    ports:
      - 5672:5672
      - 15672:15672

  postgres:
    image: postgres:10
    container_name: dataflow-postgres
    restart: always
    environment:
      POSTGRES_DB: dataflow
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpw
    expose:
      - 5432
    ports:
      - 5432:5432

  dataflow-server:
    build: ./docker/spring-cloud-dataflow-server
    container_name: dataflow-server
    ports:
      - "9393:9393"
    environment:
      - spring.cloud.dataflow.applicationProperties.stream.spring.rabbitmq.host=rabbitmq
      - spring.cloud.skipper.client.serverUri=http://skipper-server:7577/api
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dataflow
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpw
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
   # entrypoint: "./wait-for-it.sh -t 240 postgres:5432 -- java -jar /maven/spring-cloud-dataflow-server.jar"
    depends_on:
      - rabbitmq
    volumes:
      - ./docker:/apps

  skipper-server:
    build: ./docker/spring-cloud-skipper-server
    container_name: skipper
    ports:
      - "7577:7577"
      - "9000-9010:9000-9010"
      - "20000-20105:20000-20105"
    environment:
      - SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_LOCAL_ACCOUNTS_DEFAULT_PORTRANGE_LOW=20000
      - SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_LOCAL_ACCOUNTS_DEFAULT_PORTRANGE_HIGH=20100
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dataflow
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpw
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
    entrypoint: "./wait-for-it.sh -t 240 postgres:5432 -- java -Djava.security.egd=file:/dev/./urandom -jar /spring-cloud-skipper-server.jar"
    volumes:
      - ./docker:/apps